- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_65'
  min: 3001
  max: 3100
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_68'
  min: 3301
  max: 3400
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_59'
  min: 2401
  max: 2500
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_55'
  min: 2001
  max: 2100
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_64'
  min: 2901
  max: 3000
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_60'
  min: 2501
  max: 2600
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_62'
  min: 2701
  max: 2800
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_74'
  min: 3901
  max: 4000
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_67'
  min: 3201
  max: 3300
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_47'
  min: 1201
  max: 1300
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_63'
  min: 2801
  max: 2900
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_58'
  min: 2301
  max: 2400
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_49'
  min: 1401
  max: 1500
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_48'
  min: 1301
  max: 1400
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_69'
  min: 3401
  max: 3500
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_43'
  min: 0
  max: 1000
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_71'
  min: 3601
  max: 3700
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_72'
  min: 3701
  max: 3800
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_61'
  min: 2601
  max: 2700
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#4001'
  min: 4001
  max: 9999
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_73'
  min: 3801
  max: 3900
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_51'
  min: 1601
  max: 1700
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_45'
  min: 1001
  max: 1100
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_53'
  min: 1801
  max: 1900
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_56'
  min: 2101
  max: 2200
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_46'
  min: 1101
  max: 1200
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_70'
  min: 3501
  max: 3600
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_50'
  min: 1501
  max: 1600
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_54'
  min: 1901
  max: 2000
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_66'
  min: 3101
  max: 3200
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_52'
  min: 1701
  max: 1800
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#AvCheck_57'
  min: 2201
  max: 2300