- min: 131
  max: 135
  uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_30'
- min: 191
  max: 195
  uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_30'
- min: 156
  max: 160
  uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_30'
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_27'
  min: 116
  max: 120
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_10'
  min: 31
  max: 35
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_34'
  min: 151
  max: 155
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_29'
  min: 126
  max: 130
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_19'
  min: 76
  max: 80
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_24'
  min: 101
  max: 105
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_17'
  min: 66
  max: 70
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_25'
  min: 106
  max: 110
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_6'
  min: 11
  max: 15
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_4'
  min: 0
  max: 5
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_7'
  min: 16
  max: 20
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_41'
  min: 186
  max: 190
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_26'
  min: 111
  max: 115
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_18'
  min: 71
  max: 75
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_8'
  min: 21
  max: 25
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_32'
  min: 141
  max: 145
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_33'
  min: 146
  max: 150
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_21'
  min: 86
  max: 90
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_37'
  min: 161
  max: 170
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_39'
  min: 176
  max: 180
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_28'
  min: 121
  max: 125
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_22'
  min: 91
  max: 95
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_16'
  min: 61
  max: 65
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_13'
  min: 46
  max: 50
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_43'
  min: 196
  max: 200
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_40'
  min: 181
  max: 185
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_14'
  min: 51
  max: 55
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_15'
  min: 56
  max: 60
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_5'
  min: 6
  max: 10
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_12'
  min: 41
  max: 45
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_38'
  min: 171
  max: 175
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_9'
  min: 26
  max: 30
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_51'
  min: 201
  max: 999
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_31'
  min: 136
  max: 140
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_11'
  min: 36
  max: 40
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_23'
  min: 96
  max: 100
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_36'
  min: 161
  max: 165
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ImplPlan_20'
  min: 81
  max: 85