- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_20'
  val: 2.8
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_34'
  val: 4.2
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_5'
  val: 1.3
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_22'
  val: 3.0
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#5.0'
  val: 5.0
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_16'
  val: 2.4
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_41'
  val: 4.9
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_21'
  val: 2.9
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_14'
  val: 2.2
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_23'
  val: 3.1
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_24'
  val: 3.2
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_6'
  val: 1.4
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_7'
  val: 1.5
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_33'
  val: 4.1
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_9'
  val: 1.7
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_17'
  val: 2.5
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_36'
  val: 4.4
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_38'
  val: 4.6
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_32'
  val: 4.0
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_3'
  val: 1.1
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_1'
  val: 1.0
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_26'
  val: 3.4
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_37'
  val: 4.5
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_39'
  val: 4.7
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_30'
  val: 3.8
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_18'
  val: 2.6
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_35'
  val: 4.3
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_13'
  val: 2.1
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_15'
  val: 2.3
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_25'
  val: 3.3
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_11'
  val: 1.9
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_8'
  val: 1.6
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_10'
  val: 1.8
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_4'
  val: 1.2
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_27'
  val: 3.5
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_31'
  val: 3.9
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_29'
  val: 3.7
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_19'
  val: 2.7
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_40'
  val: 4.8
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_12'
  val: 2.0
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#ItemsCount_28'
  val: 3.6