- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_107'
  min: 151
  max: 160
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_103'
  min: 111
  max: 120
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_112'
  min: 201
  max: 999
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_109'
  min: 171
  max: 180
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_105'
  min: 131
  max: 140
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_92'
  min: 0
  max: 10
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_100'
  min: 81
  max: 90
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_110'
  min: 181
  max: 190
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_94'
  min: 21
  max: 30
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_108'
  min: 161
  max: 170
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_102'
  min: 101
  max: 110
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_99'
  min: 71
  max: 80
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_97'
  min: 51
  max: 60
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_104'
  min: 121
  max: 130
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_111'
  min: 191
  max: 200
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_101'
  min: 91
  max: 100
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_98'
  min: 61
  max: 70
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_95'
  min: 31
  max: 40
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_93'
  min: 11
  max: 20
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_96'
  min: 41
  max: 50
- uri: 'http://www.owl-ontologies.com/PersonalManagement.owl#TotalChecksCount_106'
  min: 141
  max: 150